FROM node:22-slim

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml vite.config.ts ./

RUN pnpm install --frozen-lockfile

EXPOSE 4200

CMD ["pnpm", "dev"]
# CMD ["sleep", "infinity"]
