FROM squidfunk/mkdocs-material:9.6.20

RUN pip install mkdocs-awesome-nav mkdocs-glightbox

WORKDIR /workspace

COPY . /workspace/

EXPOSE 8000

CMD ["serve", "-f", "/workspace/mkdocs.yml", "-a", "0.0.0.0:8000"]
